# Generated by Django 4.1.7 on 2023-03-11 17:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mainapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('doctor_surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('job_title', models.CharField(max_length=50, verbose_name='Должность')),
            ],
        ),
        migrations.CreateModel(
            name='EcgData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecg_hea_data', models.FileField(blank=True, upload_to=mainapp.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('hea',), message='Файлы должны иметь разрешение .hea')], verbose_name='Данные ЭКГ')),
                ('ecg_dat_data', models.FileField(blank=True, upload_to=mainapp.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('dat',), message='Файлы должны иметь разрешение .dat')], verbose_name='Данные ЭКГ')),
                ('ecg_image', models.ImageField(blank=True, upload_to=mainapp.models.user_directory_path, verbose_name='Изображение ЭКГ')),
                ('normal', models.FloatField(verbose_name='Нормальный синусовый ритм')),
                ('arrhythm', models.FloatField(verbose_name='Аритмия')),
                ('atrial_fib', models.FloatField(verbose_name='Мерцательная аритмия')),
                ('mal_vent_ect', models.FloatField(verbose_name='Злокачественная желудочковая эктопия')),
                ('sup_arrh', models.FloatField(verbose_name='Наджелудочковая аритмия')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50, verbose_name='Имя пациента')),
                ('patient_surname', models.CharField(max_length=50, verbose_name='Фамилия пациента')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата проведения ЭКГ')),
                ('doctor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.doctor', verbose_name='Лечащий врач')),
                ('patient_ecg', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.ecgdata', verbose_name='Данные ЭКГ')),
            ],
        ),
    ]
