# Generated by Django 4.1.7 on 2023-03-11 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_patient_patient_ecg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_ecg',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.ecgdata', verbose_name='Пациент'),
        ),
    ]
