# Generated by Django 4.1.7 on 2023-03-11 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_patient_patient_ecg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_ecg',
        ),
        migrations.AddField(
            model_name='ecgdata',
            name='patient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.patient', verbose_name='Пациент'),
        ),
    ]
