# Generated by Django 4.1.7 on 2023-03-11 20:38

from django.db import migrations, models
import django.db.models.deletion
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_patient_patient_ecg_ecgdata_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecgdata',
            old_name='ecg_dat_data',
            new_name='ecg_dat_file',
        ),
        migrations.RenameField(
            model_name='ecgdata',
            old_name='ecg_hea_data',
            new_name='ecg_hea_file',
        ),
        migrations.RemoveField(
            model_name='ecgdata',
            name='arrhythm',
        ),
        migrations.RemoveField(
            model_name='ecgdata',
            name='atrial_fib',
        ),
        migrations.RemoveField(
            model_name='ecgdata',
            name='ecg_image',
        ),
        migrations.RemoveField(
            model_name='ecgdata',
            name='mal_vent_ect',
        ),
        migrations.RemoveField(
            model_name='ecgdata',
            name='normal',
        ),
        migrations.RemoveField(
            model_name='ecgdata',
            name='sup_arrh',
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecg_image', models.ImageField(blank=True, upload_to=mainapp.models.user_directory_path, verbose_name='Изображение ЭКГ')),
                ('normal', models.FloatField(verbose_name='Нормальный синусовый ритм')),
                ('arrhythm', models.FloatField(verbose_name='Аритмия')),
                ('atrial_fib', models.FloatField(verbose_name='Мерцательная аритмия')),
                ('mal_vent_ect', models.FloatField(verbose_name='Злокачественная желудочковая эктопия')),
                ('sup_arrh', models.FloatField(verbose_name='Наджелудочковая аритмия')),
                ('patient', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.patient', verbose_name='Пациент')),
            ],
        ),
    ]
